### ISSUE TITLE
looks complicated

### ISSUE THREAD

**Issue by Roizor** [AdamEXu/SasHax#1]
why not just parse the entire file as json? it is json anyways and will be much easier for you

check out [sasquatch-explorer](https://github.com/roizor/sasquatch-explorer)

**Comment by AdamEXu** [comment]
i guess but im a stupid, plus this isn't being developed anymore as I'm developing a client to edit the game's code and mod the game, kinda like a mod client

**Comment by AdamEXu** [comment]
updates soon

**Comment by Roizor** [comment]
hey there, could i help you? dm me on discord over at Roi#9999

**Comment by Roizor** [comment]
hey

**Comment by AdamEXu** [comment]
uhh hi?

**Comment by AdamEXu** [comment]
yea i got a cease of desist from the developers or smth

**Comment by Roizor** [comment]
oh ok nvm
